### ISSUE TITLE
Images always link to HTTP, even when browsing over HTTPS.

### ISSUE THREAD

**Issue by rotorcowboy** [open-eats/openeats-api#15]
## Problem

As soon as OpenEats attempts to load a recipe image, Chrome complains that the web page is no longer secure because the image is served over regular HTTP.

I tracked it all the way down to [this line](https://github.com/open-eats/openeats-api/blob/727f2d12829bde6f579bf4eacddfbd9adbd23a49/v1/recipe/serializers.py#L33), where the API attempts to build an absolute URI to the resource:

```
request = self.context.get('request', None)
if request is not None:
    return request.build_absolute_uri(url)
```

For example, if browsing at "https://recipes.example.com", a recipe image will have an image URL like this:

```
http://recipes.example.com/site-media/CACHE/images/upload/recipe_photos/beets/08eff495c6a8752626c07854fbbc797e.jpg
```

This, of course, forces the browser to attempt to retrieve the resource over HTTP. I'm guessing this happens because all requests sent to the API are over HTTP, so that's all Django has to build an absolute URI.

## Proposed solution

If you remove those three lines I mentioned above, the image URL will look like this:

```
/site-media/CACHE/images/upload/recipe_photos/beets/08eff495c6a8752626c07854fbbc797e.jpg
```

The scheme, domain, and port are stripped from the image URL, but the browser will still attempt to fetch it from the same origin.

Do you see this as an acceptable solution to this problem? I've only tested it in my environment, but I think it should work for anyone.

Thanks!

**Comment by RyanNoelk** [comment]
Hey!

I believe the root cause of the problem here is that Django thinks you are serving over http rather than https. If you are using docker or have the API behind a http proxy (like apache or nginx) then you need to [set `HTTP_X_FORWARDED_PROTO` to True](https://github.com/open-eats/OpenEats/blob/master/docs/Setting_up_env_file.md#http_x_forwarded_proto).

If you have that set properly then this shouldn't be an issue. My personal instance works fine like this. If the issue persists then please open a pull request with the change you propose and I'll take a deep look. 

My only hesitation is that overwriting that line may fix the issue now, but only because I'm overwriting the base class. If there is ever a refactor then taking this into account could cause issues.

Thanks!
-Ryan

**Comment by rotorcowboy** [comment]
Ah, you found it! I did have the `HTTP_X_FORWARDED_PROTO` option set to true, but I have another nginx proxy in front of the OpenEats nginx server. Adding it to my first proxy config did the trick.

```
server {
    listen 443 ssl;
    server_name recipes.example.com;
    ...
    location / {
        proxy_pass http://localhost:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }
}
```

Thanks a ton!
